{
    "version": 2,
    "updates": [
        {
            "allow": [
                {
                    "dependency-type": "all"
                }
            ],
            "directory": "/",
            "package-ecosystem": "composer",
            "schedule": {
                "interval": "daily"
            },
            "versioning-strategy": "increase"
        },
        {
            "allow": [
                {
                    "dependency-type": "all"
                }
            ],
            "directory": "/",
            "package-ecosystem": "npm",
            "schedule": {
                "interval": "daily"
            },
            "versioning-strategy": "increase"
        },
        {
            "directory": "/",
            "package-ecosystem": "docker",
            "schedule": {
                "interval": "daily"
            }
        }
        {
            "directory": "/",
            "package-ecosystem": "github-actions",
            "schedule": {
                "interval": "daily"
            }
        }
    ]
}
