name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    name: Build CI container
    runs-on: ubuntu-latest
    steps:
      - name: "Install BuildX"
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: "Build docker image"
        run: |
          docker buildx build \
            --load \
            --target=development \
            --tag=test-image \
            .

      - name: "Psalm"
        run: "docker run --rm --entrypoint=bash test-image vendor/bin/psalm"

      - name: "PHPUnit"
        run: "docker run --rm --entrypoint=bash test-image vendor/bin/phpunit"

      - name: "PHPCS"
        run: "docker run --rm --entrypoint=bash test-image vendor/bin/phpcs"
