name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    name: Build CI container
    runs-on: ubuntu-latest
    steps:
      - name: "Install BuildX"
        uses: docker/setup-buildx-action@v1

      - name: "ghcr.io login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: "Build docker image"
        uses: docker/build-push-action@v2
        with:
          context: .
          target: development
          push: false
          tags: ghcr.io/roave/docbooktool-ci:${{ github.sha }}
          cache-to: type=registry,ref=ghcr.io/roave/docbooktool-ci:ci-cache
          cache-from: |
            type=registry,ref=ghcr.io/roave/docbooktool-ci:ci-cache

      - name: "Psalm"
        run: "docker run --rm --entrypoint=bash ghcr.io/roave/docbooktool-ci:${{ github.sha }} vendor/bin/psalm"

      - name: "PHPUnit"
        run: "docker run --rm --entrypoint=bash ghcr.io/roave/docbooktool-ci:${{ github.sha }} vendor/bin/phpunit"

      - name: "PHPCS"
        run: "docker run --rm --entrypoint=bash ghcr.io/roave/docbooktool-ci:${{ github.sha }} vendor/bin/phpcs"
