name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    name: Build CI container
    runs-on: ubuntu-latest
    steps:
      - name: "Install BuildX"
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: "Build docker image"
        uses: "docker/build-push-action@v2"
        with:
          target: "development"
          tags: "ghcr.io/roave/docbooktool:test-image"
          push: "false"
          load: "true"
          cache-from: "type=gha,scope=ci-cache"
          cache-to: "type=gha,mode=max,scope=ci-cache"

      - name: "Psalm"
        run: "docker run --rm --entrypoint=php ghcr.io/roave/docbooktool:test-image vendor/bin/psalm"

      - name: "PHPUnit"
        run: "docker run --rm --entrypoint=php ghcr.io/roave/docbooktool:test-image vendor/bin/phpunit"

      - name: "PHPCS"
        run: "docker run --rm --entrypoint=php ghcr.io/roave/docbooktool:test-image vendor/bin/phpcs"
